### ISSUE TITLE
Problem of Pyglet in Visualization of Simulation

### ISSUE THREAD

**Issue by minglou1984** [Zhehui-Huang/quad-swarm-rl#85]
When i visualize the simulation, i meet the follow problems of Pyglet. How can i do it?

IMPORTING OPENGL RENDERING MODULE. THIS SHOULD NOT BE IMPORTED IN HEADLESS MODE!
Traceback (most recent call last):
  File "/home/madrl/code/quad-swarm-rl-master/swarm_rl/enjoy.py", line 34, in <module>
    sys.exit(main())
  File "/home/madrl/code/quad-swarm-rl-master/swarm_rl/enjoy.py", line 12, in main
    status = enjoy(cfg)
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/sample_factory/enjoy.py", line 169, in enjoy
    last_render_start = render_frame(cfg, env, video_frames, num_episodes, last_render_start)
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/sample_factory/enjoy.py", line 78, in render_frame
    env.render()
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/home/madrl/code/quad-swarm-rl-master/swarm_rl/env_wrappers/compatibility.py", line 57, in render
    return self.env.render()
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/quadrotor_multi.py", line 736, in render
    self.scenes[i].update_env(self.room_dims)
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 211, in update_env
    self._make_scene()
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 289, in _make_scene
    world.build(batch)
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/rendering3d.py", line 273, in build
    self._build_children(batch)
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/rendering3d.py", line 260, in _build_children
    c.build(batch, self.pyg_grp)
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/rendering3d.py", line 312, in build
    c.build(batch, ordering)
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/rendering3d.py", line 402, in build
    self.pyg_grp = _PygTexture(tex=self.tex,
  File "/home/madrl/code/quad-swarm-rl-master/gym_art/quadrotor_multi/rendering3d.py", line 503, in __init__
    glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, anisotropy)
  File "/home/madrl/.conda/envs/madrl/lib/python3.8/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid enumerant'

**Comment by ali-kosemen** [comment]
I got a similar error. The error was about ogenGL library.

**Comment by Zhehui-Huang** [comment]
Have you tried to set `--quads_render=True`?

**Comment by ali-kosemen** [comment]
My OS, 

--------------------------------------------
                                 
*I'm working on Ubuntu 24.04* 

--------------------------------------------

Yes I tried but I got this error:


(quadrotor_swarm) (base) aliksmn@aliksmn:~/cursor_ai/quadrotor_swarm$ python -m swarm_rl.enjoy --algo=APPO --env=quadrotor_multi --replay_buffer_sample_prob=0 --quads_use_numba=False --quads_render=True --train_dir=./train_dir/paper_quads_multi_mix_baseline_8a_attn_v116/single_  --experiment=00_single_see_0 --quads_view_mode topdown
[2025-01-18 12:19:38,799][14668] register_encoder_factory: <function make_quadmulti_encoder at 0x79cdf5b0c220>
[2025-01-18 12:19:38,815][14668] Loading existing experiment configuration from ./train_dir/paper_quads_multi_mix_baseline_8a_attn_v116/single_/00_single_see_0/config.json
[2025-01-18 12:19:38,816][14668] Overriding arg 'quads_use_numba' with value False passed from command line
[2025-01-18 12:19:38,816][14668] Overriding arg 'replay_buffer_sample_prob' with value 0.0 passed from command line
[2025-01-18 12:19:38,816][14668] Overriding arg 'quads_view_mode' with value ['topdown'] passed from command line
[2025-01-18 12:19:38,816][14668] Overriding arg 'quads_render' with value True passed from command line
[2025-01-18 12:19:38,816][14668] Adding new argument 'fps'=0 that is not in the saved config file!
[2025-01-18 12:19:38,816][14668] Adding new argument 'eval_env_frameskip'=None that is not in the saved config file!
[2025-01-18 12:19:38,816][14668] Adding new argument 'no_render'=False that is not in the saved config file!
[2025-01-18 12:19:38,816][14668] Adding new argument 'save_video'=False that is not in the saved config file!
[2025-01-18 12:19:38,816][14668] Adding new argument 'video_frames'=1000000000.0 that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'video_name'=None that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'max_num_frames'=1000000000.0 that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'max_num_episodes'=1000000000.0 that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'push_to_hub'=False that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'hf_repository'=None that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'policy_index'=0 that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'eval_deterministic'=False that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'train_script'=None that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Adding new argument 'enjoy_script'=None that is not in the saved config file!
[2025-01-18 12:19:38,817][14668] Using frameskip 1 and render_action_repeat=1 for evaluation
/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/gymnasium/spaces/box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float32
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Observation components: ['xyz', 'vxyz', 'R', 'omega']
[2025-01-18 12:19:40,635][14668] Loading state from checkpoint ./train_dir/paper_quads_multi_mix_baseline_8a_attn_v116/single_/00_single_see_0/checkpoint_p0/checkpoint_000001276_1306624.pth...
/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/sample_factory/algo/learning/learner.py:281: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint_dict = torch.load(latest_checkpoint, map_location=device)
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: iris
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/aliksmn/cursor_ai/quadrotor_swarm/swarm_rl/enjoy.py", line 17, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aliksmn/cursor_ai/quadrotor_swarm/swarm_rl/enjoy.py", line 12, in main
    status = enjoy(cfg)
             ^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/sample_factory/enjoy.py", line 169, in enjoy
    last_render_start = render_frame(cfg, env, video_frames, num_episodes, last_render_start)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/sample_factory/enjoy.py", line 78, in render_frame
    env.render()
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
           ^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
           ^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
           ^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/cursor_ai/quadrotor_swarm/swarm_rl/env_wrappers/compatibility.py", line 57, in render
    return self.env.render()
           ^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
           ^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/cursor_ai/quadrotor_swarm/gym_art/quadrotor_multi/quadrotor_multi.py", line 730, in render
    self.init_scene_multi()
  File "/home/aliksmn/cursor_ai/quadrotor_swarm/gym_art/quadrotor_multi/quadrotor_multi.py", line 330, in init_scene_multi
    self.scenes.append(Quadrotor3DSceneMulti(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/cursor_ai/quadrotor_swarm/gym_art/quadrotor_multi/quadrotor_multi_visualization.py", line 124, in __init__
    self.pygl_window = __import__('pyglet.window', fromlist=['key'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/window/__init__.py", line 1918, in <module>
    gl._create_shadow_window()
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/gl/__init__.py", line 206, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/window/__init__.py", line 615, in __init__
    context = config.create_context(gl.current_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/aliksmn/anaconda3/envs/quadrotor_swarm/lib/python3.11/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

@Zhehui-Huang

**Comment by Zhehui-Huang** [comment]
Not sure if this is something about the code since I have never encountered this issue before. I tested my code on Ubuntu 18.04, Ubuntu 20.04, and Ubuntu 24.04 before, and all of them worked well. I posted your questions on Claude, and I got the following answer:

It looks like you're running into a graphics-related error while trying to render a quadrotor swarm simulation. The key issues appear to be:

1. Missing graphics drivers, specifically the Intel iris and software rendering (swrast) drivers:
```
MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file
```

2. Ultimately failing to create an OpenGL context:
```
pyglet.gl.ContextException: Could not create GL context
```

To fix this, you'll need to:

1. Install the missing Mesa drivers. On Ubuntu/Debian you can do this with:
```bash
sudo apt-get update
sudo apt-get install mesa-utils libegl1-mesa libgl1-mesa-dri libgl1-mesa-glx
```

2. If you're running this on a remote machine or in a environment without proper GPU access, you may need to:
   - Either set up X11 forwarding properly if connecting via SSH
   - Or use a software renderer like xvfb:
```bash
sudo apt-get install xvfb
xvfb-run python -m swarm_rl.enjoy [your other arguments]
```

**Comment by ali-kosemen** [comment]
Thank you so much for your effort. I tried installing Mesa drivers and xvfb software renderer. But the problem is continuing. I hope to find a solution soon. If I don't, what do you suggest. Would it make sense to try a different simulation environment (Framework or Unity etc.) ?

@Zhehui-Huang

**Comment by Zhehui-Huang** [comment]
Could you check if you are using `pyglet==1.5.23`? Our simulator does not support the latest version of Pyglet.

If that still does not work, the final thing you might can try is to reinstall the conda environment.

**Comment by ali-kosemen** [comment]
Hello @Zhehui-Huang ,

It’s been a while since we last talked. Unfortunately, I wasn’t able to solve the issue we discussed previously. That’s why I made a decision — both for myself and for others who might be facing similar problems. I decided to use Three.js for visualization (Web).

In addition, to increase the diversity of the project, I’ve added a new scenario. With your permission, I would love to share this project on LinkedIn as part of my Computer Engineering undergraduate final project and credit you and your paper as references.

If you’d like, you can also integrate the new scenario into your current work. You can find it in the scenarios folder as ep_figure8_lemniscate.py.

Thank you so much for everything.

Here is my repo link: https://github.com/ali-kosemen/quadrotor-swarm

**Comment by Zhehui-Huang** [comment]
HI @ali-kosemen ,

Great work! Please feel free to share it on LinkedIn, just make sure to credit our work.

Best,
Zhehui
